apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector: 
    name: foo
---
apiVersion: v1
kind: Pod
metadata:
  name: foo
  labels:
    name: foo
spec:
  containers:
  - image: golang:alpine
    name: foo
    command: ["go", "run", "goweb.go"]
    workingDir: "/home/foo/golang-sample"
    volumeMounts:
    - mountPath: /home/foo
      name: git-volume
    resources:
      requests:
        cpu: 200m
  volumes:
  - name: git-volume
    gitRepo:
      repository: "https://github.com/tenxcloud/golang-sample.git"
      revision: "master"
